package com.myapp.struts;
// Generated Apr 25, 2015 10:09:26 AM by Hibernate Tools 3.2.1.GA



/**
 * Confirmation generated by hbm2java
 */
public class Confirmation extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private ConfirmationId id;
     private Orders orders;
     private Buyers buyers;
     private Product product;

    public Confirmation() {
    }

    public Confirmation(ConfirmationId id, Orders orders, Buyers buyers, Product product) {
       this.id = id;
       this.orders = orders;
       this.buyers = buyers;
       this.product = product;
    }
   
    public ConfirmationId getId() {
        return this.id;
    }
    
    public void setId(ConfirmationId id) {
        this.id = id;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public Buyers getBuyers() {
        return this.buyers;
    }
    
    public void setBuyers(Buyers buyers) {
        this.buyers = buyers;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }




}


