package com.myapp.struts;
// Generated Apr 25, 2015 10:09:26 AM by Hibernate Tools 3.2.1.GA



/**
 * ConfirmationId generated by hbm2java
 */
public class ConfirmationId  implements java.io.Serializable {


     private int prdno;
     private int ordid;
     private String uname;

    public ConfirmationId() {
    }

    public ConfirmationId(int prdno, int ordid, String uname) {
       this.prdno = prdno;
       this.ordid = ordid;
       this.uname = uname;
    }
   
    public int getPrdno() {
        return this.prdno;
    }
    
    public void setPrdno(int prdno) {
        this.prdno = prdno;
    }
    public int getOrdid() {
        return this.ordid;
    }
    
    public void setOrdid(int ordid) {
        this.ordid = ordid;
    }
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConfirmationId) ) return false;
		 ConfirmationId castOther = ( ConfirmationId ) other; 
         
		 return (this.getPrdno()==castOther.getPrdno())
 && (this.getOrdid()==castOther.getOrdid())
 && ( (this.getUname()==castOther.getUname()) || ( this.getUname()!=null && castOther.getUname()!=null && this.getUname().equals(castOther.getUname()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPrdno();
         result = 37 * result + this.getOrdid();
         result = 37 * result + ( getUname() == null ? 0 : this.getUname().hashCode() );
         return result;
   }   


}


