package com.myapp.struts;
// Generated Apr 25, 2015 10:09:26 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders extends org.apache.struts.action.ActionForm  implements java.io.Serializable {


      private String username;
      private int ordid;
     private Buyers buyers;
     private String orderdt;
     private String ordtime;
     private Integer ordamnt;
     private Set products = new HashSet(0);
     private Set confirmations = new HashSet(0);

    public Orders() {
    }

	
    public Orders(int ordid) {
        this.ordid = ordid;
    }
    public Orders(int ordid, Buyers buyers, String orderdt, String ordtime, Integer ordamnt, Set products, Set confirmations) {
       this.ordid = ordid;
       this.buyers = buyers;
       this.orderdt = orderdt;
       this.ordtime = ordtime;
       this.ordamnt = ordamnt;
       this.products = products;
       this.confirmations = confirmations;
    }
   
    public int getOrdid() {
        return this.ordid;
    }
    
    public void setOrdid(int ordid) {
        this.ordid = ordid;
    }
    public Buyers getBuyers() {
        return this.buyers;
    }
    
    public void setBuyers(Buyers buyers) {
        this.buyers = buyers;
    }
    public String getOrderdt() {
        return this.orderdt;
    }
    
    public void setOrderdt(String orderdt) {
        this.orderdt = orderdt;
    }
    public String getOrdtime() {
        return this.ordtime;
    }
    
    public void setOrdtime(String ordtime) {
        this.ordtime = ordtime;
    }
    public Integer getOrdamnt() {
        return this.ordamnt;
    }
    
    public void setOrdamnt(Integer ordamnt) {
        this.ordamnt = ordamnt;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }
    public Set getConfirmations() {
        return this.confirmations;
    }
    
    public void setConfirmations(Set confirmations) {
        this.confirmations = confirmations;
    }

    /**
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * @param username the username to set
     */
    public void setUsername(String username) {
        this.username = username;
    }




}


