package com.myapp.struts;
// Generated Apr 25, 2015 10:09:26 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Productcat generated by hbm2java
 */
public class Productcat extends org.apache.struts.action.ActionForm  implements java.io.Serializable {


     private int procatid;
     private String procatname;
     private Set products = new HashSet(0);

    public Productcat() {
    }

	
    public Productcat(int procatid) {
        this.procatid = procatid;
    }
    public Productcat(int procatid, String procatname, Set products) {
       this.procatid = procatid;
       this.procatname = procatname;
       this.products = products;
    }
   
    public int getProcatid() {
        return this.procatid;
    }
    
    public void setProcatid(int procatid) {
        this.procatid = procatid;
    }
    public String getProcatname() {
        return this.procatname;
    }
    
    public void setProcatname(String procatname) {
        this.procatname = procatname;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


