package com.myapp.struts;
// Generated Apr 25, 2015 10:09:26 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import org.apache.struts.upload.FormFile;

/**
 * Product generated by hbm2java
 */
public class Product extends org.apache.struts.action.ActionForm  implements java.io.Serializable {


     private int prdno;
     private Productcat productcat;
     private String prdname;
     private Integer price;
     private String description;
     private String mfg;
     private String photo;
     private Set orderses = new HashSet(0);
     private Set confirmations = new HashSet(0);
     private FormFile pic;
     private int procatid;
    



    public Product() {
    }

	
    public Product(int prdno) {
        this.prdno = prdno;
    }
    public Product(int prdno, Productcat productcat, String prdname, Integer price, String description, String mfg, String photo, Set orderses, Set confirmations) {
       this.prdno = prdno;
       this.productcat = productcat;
       this.prdname = prdname;
       this.price = price;
       this.description = description;
       this.mfg = mfg;
       this.photo = photo;
       this.orderses = orderses;
       this.confirmations = confirmations;
    }
   
    public int getPrdno() {
        return this.prdno;
    }
    
    public void setPrdno(int prdno) {
        this.prdno = prdno;
    }
    public Productcat getProductcat() {
        return this.productcat;
    }
    
    public void setProductcat(Productcat productcat) {
        this.productcat = productcat;
    }
    public String getPrdname() {
        return this.prdname;
    }
    
    public void setPrdname(String prdname) {
        this.prdname = prdname;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getMfg() {
        return this.mfg;
    }
    
    public void setMfg(String mfg) {
        this.mfg = mfg;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getConfirmations() {
        return this.confirmations;
    }
    
    public void setConfirmations(Set confirmations) {
        this.confirmations = confirmations;
    }

    /**
     * @return the pic
     */
    public FormFile getPic() {
        return pic;
    }

    /**
     * @param pic the pic to set
     */
    public void setPic(FormFile pic) {
        this.pic = pic;
    }

    /**
     * @return the procatid
     */
    public int getProcatid() {
        return procatid;
    }

    /**
     * @param procatid the procatid to set
     */
    public void setProcatid(int procatid) {
        this.procatid = procatid;
    }




}


